BN_CATEGORIES = [
        # Fiction & Literature
        "Folklore & Mythology",
        "General Fiction",
        "Graphic Novels & Comics",
        "Historical Fiction",
        "Horror",
        "Literary Fiction",
        "Literature",
        "Manga",
        "Mystery",
        "Poetry",
        "Romance",
        "Science Fiction & Fantasy",
        "Thrillers",
        "Westerns",

        # Nonfiction
        "Activity & Game Books",
        "African-American Studies",
        "Antiques & Collectibles",
        "Art, Architecture & Photography",
        "Astrology & Tarot",
        "Bibles & Christianity",
        "Biography",
        "Business Books",
        "Computers",
        "Cookbooks, Food & Wine",
        "Crafts & Hobbies",
        "Crossword Puzzle Books",
        "Current Affairs & Politics",
        "Diet, Health & Fitness",
        "Economics",
        "Education",
        "Engineering",
        "European History",
        "Fashion & Costume",
        "Foreign Languages",
        "History",
        "Home & Garden",
        "Humor",
        "Law",
        "LGBTQIA+ Studies",
        "Medicine & Nursing Books",
        "Military History",
        "Music",
        "Nature",
        "New Age & Alternative Beliefs",
        "The Outdoors",
        "Parenting & Family",
        "Performing Arts",
        "Pets",
        "Philosophy",
        "Psychology",
        "Reference",
        "Religion",
        "Role-Playing & Fantasy Games",
        "Science & Technology",
        "Self-Help & Relationships",
        "Social Sciences",
        "Sociology",
        "Sports",
        "Study Aids & Test Prep",
        "Transportation",
        "Travel",
        "True Crime",
        "United States History",
        "United States Politics",
        "Weddings",
        "Women's Studies",
        "World History"
    ]